CREATE TABLESPACE <tbsp> DATAFILE '<location>' SIZE 1024M REUSE AUTOEXTEND ON NEXT 10240K MAXSIZE 32767M LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

CREATE USER <user> IDENTIFIED BY <password> DEFAULT TABLESPACE <tbsp>;

CREATE DIRECTORY <dir> AS '<location>';
GRANT READ, WRITE ON DIRECTORY <dir> TO <user>;

